spring:
  application:
    name: followtry-cloud
  cloud:
    config:
      server:
        git:
          uri:
          local:
            pattern: local*
            uri: file:/Users/jingzhongzhi/git-project/tickle
          search-paths: followtry-cloud/src/main/resources/*
      profile: dev
      label: trunk
      uri: ["http://localhost:8888"]
server:
  port: 8080

followtry:
  name: followtry-cloud
  home: ["http://www.baidu.com"]
