server:
  port: 8080

spring:
  devtools:
    add-properties: false
  profiles:
    active: local
  http:
    log-request-details: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    username: hotel_report
#    password: Umwn5PoglrVU5R
    #    url: jdbc:mysql://10.24.98.22:5002/hotel_report?characterEncoding=utf8
    username: brief
    password: brief
    url: jdbc:mysql://127.0.0.1:3306/brief?characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource



logging:
  level:
    org.springframework: info


mybatis:
  mapper-locations:
    - classpath*:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml
#  type-aliases-package: cn.followtry.boot.java.mybatis
#  type-handlers-package: cn.followtry.boot.java.mybatis

#my-scanner.base-package=cn.followtry.boot



