server:
  port: 8080

spring:
  devtools:
    add-properties: false
  http:
    log-request-details: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: brief
    password: brief
    url: jdbc:mysql://127.0.0.1:3006/brief?characterEncoding=utf-8



logging:
  level:
    org.springframework: info


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: cn.followtry.boot.java.mybatis
  type-handlers-package: cn.followtry.boot.java.mybatis

#my-scanner.base-package=cn.followtry.boot



